# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/himno',
                'doc_host': 'https://civvic.github.io',
                'git_url': 'https://github.com/civvic/himno',
                'lib_path': 'himno'},
  'syms': {'himno.core': {'himno.core.foo': ('core.html#foo', 'himno/core.py')}}}
